# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: upi.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'upi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tupi.proto\x12\x03upi\"I\n\x0c\x44\x65\x62itRequest\x12\x11\n\tsender_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"U\n\rDebitResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08\x61pproved\x18\x02 \x01(\x08\x12\x12\n\naccount_id\x18\x03 \x01(\t\x12\x0e\n\x06reason\x18\x04 \x01(\t\")\n\x0fRollbackRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\"2\n\x10RollbackResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\"b\n\x0cRouteRequest\x12\x16\n\x0etransaction_id\x18\x01 \x01(\t\x12\x13\n\x0bsender_bank\x18\x02 \x01(\t\x12\x15\n\rreceiver_bank\x18\x03 \x01(\t\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\"7\n\rRouteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x16\n\x0etransaction_id\x18\x02 \x01(\t\"L\n\rCreditRequest\x12\x13\n\x0breceiver_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x01\x12\x16\n\x0etransaction_id\x18\x03 \x01(\t\"@\n\x0e\x43reditResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63k_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t2\x81\x01\n\x11SenderBankService\x12.\n\x05\x44\x65\x62it\x12\x11.upi.DebitRequest\x1a\x12.upi.DebitResponse\x12<\n\rRollbackDebit\x12\x14.upi.RollbackRequest\x1a\x15.upi.RollbackResponse2C\n\x11NPCISwitchService\x12.\n\x05Route\x12\x11.upi.RouteRequest\x1a\x12.upi.RouteResponse2H\n\x13ReceiverBankService\x12\x31\n\x06\x43redit\x12\x12.upi.CreditRequest\x1a\x13.upi.CreditResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'upi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEBITREQUEST']._serialized_start=18
  _globals['_DEBITREQUEST']._serialized_end=91
  _globals['_DEBITRESPONSE']._serialized_start=93
  _globals['_DEBITRESPONSE']._serialized_end=178
  _globals['_ROLLBACKREQUEST']._serialized_start=180
  _globals['_ROLLBACKREQUEST']._serialized_end=221
  _globals['_ROLLBACKRESPONSE']._serialized_start=223
  _globals['_ROLLBACKRESPONSE']._serialized_end=273
  _globals['_ROUTEREQUEST']._serialized_start=275
  _globals['_ROUTEREQUEST']._serialized_end=373
  _globals['_ROUTERESPONSE']._serialized_start=375
  _globals['_ROUTERESPONSE']._serialized_end=430
  _globals['_CREDITREQUEST']._serialized_start=432
  _globals['_CREDITREQUEST']._serialized_end=508
  _globals['_CREDITRESPONSE']._serialized_start=510
  _globals['_CREDITRESPONSE']._serialized_end=574
  _globals['_SENDERBANKSERVICE']._serialized_start=577
  _globals['_SENDERBANKSERVICE']._serialized_end=706
  _globals['_NPCISWITCHSERVICE']._serialized_start=708
  _globals['_NPCISWITCHSERVICE']._serialized_end=775
  _globals['_RECEIVERBANKSERVICE']._serialized_start=777
  _globals['_RECEIVERBANKSERVICE']._serialized_end=849
# @@protoc_insertion_point(module_scope)
