# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import upi_pb2 as upi__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in upi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SenderBankServiceStub:
    """---------------------------------------------------------------------------
    Sender Bank gRPC Service
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Debit = channel.unary_unary(
                '/upi.SenderBankService/Debit',
                request_serializer=upi__pb2.DebitRequest.SerializeToString,
                response_deserializer=upi__pb2.DebitResponse.FromString,
                _registered_method=True)
        self.RollbackDebit = channel.unary_unary(
                '/upi.SenderBankService/RollbackDebit',
                request_serializer=upi__pb2.RollbackRequest.SerializeToString,
                response_deserializer=upi__pb2.RollbackResponse.FromString,
                _registered_method=True)


class SenderBankServiceServicer:
    """---------------------------------------------------------------------------
    Sender Bank gRPC Service
    ---------------------------------------------------------------------------
    """

    def Debit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollbackDebit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SenderBankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Debit': grpc.unary_unary_rpc_method_handler(
                    servicer.Debit,
                    request_deserializer=upi__pb2.DebitRequest.FromString,
                    response_serializer=upi__pb2.DebitResponse.SerializeToString,
            ),
            'RollbackDebit': grpc.unary_unary_rpc_method_handler(
                    servicer.RollbackDebit,
                    request_deserializer=upi__pb2.RollbackRequest.FromString,
                    response_serializer=upi__pb2.RollbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'upi.SenderBankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('upi.SenderBankService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SenderBankService:
    """---------------------------------------------------------------------------
    Sender Bank gRPC Service
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Debit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upi.SenderBankService/Debit',
            upi__pb2.DebitRequest.SerializeToString,
            upi__pb2.DebitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollbackDebit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upi.SenderBankService/RollbackDebit',
            upi__pb2.RollbackRequest.SerializeToString,
            upi__pb2.RollbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class NPCISwitchServiceStub:
    """---------------------------------------------------------------------------
    NPCI Switch Simulator gRPC Service
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Route = channel.unary_unary(
                '/upi.NPCISwitchService/Route',
                request_serializer=upi__pb2.RouteRequest.SerializeToString,
                response_deserializer=upi__pb2.RouteResponse.FromString,
                _registered_method=True)


class NPCISwitchServiceServicer:
    """---------------------------------------------------------------------------
    NPCI Switch Simulator gRPC Service
    ---------------------------------------------------------------------------
    """

    def Route(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NPCISwitchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Route': grpc.unary_unary_rpc_method_handler(
                    servicer.Route,
                    request_deserializer=upi__pb2.RouteRequest.FromString,
                    response_serializer=upi__pb2.RouteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'upi.NPCISwitchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('upi.NPCISwitchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NPCISwitchService:
    """---------------------------------------------------------------------------
    NPCI Switch Simulator gRPC Service
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Route(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upi.NPCISwitchService/Route',
            upi__pb2.RouteRequest.SerializeToString,
            upi__pb2.RouteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReceiverBankServiceStub:
    """---------------------------------------------------------------------------
    Receiver Bank gRPC Service
    ---------------------------------------------------------------------------
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Credit = channel.unary_unary(
                '/upi.ReceiverBankService/Credit',
                request_serializer=upi__pb2.CreditRequest.SerializeToString,
                response_deserializer=upi__pb2.CreditResponse.FromString,
                _registered_method=True)


class ReceiverBankServiceServicer:
    """---------------------------------------------------------------------------
    Receiver Bank gRPC Service
    ---------------------------------------------------------------------------
    """

    def Credit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiverBankServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Credit': grpc.unary_unary_rpc_method_handler(
                    servicer.Credit,
                    request_deserializer=upi__pb2.CreditRequest.FromString,
                    response_serializer=upi__pb2.CreditResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'upi.ReceiverBankService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('upi.ReceiverBankService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ReceiverBankService:
    """---------------------------------------------------------------------------
    Receiver Bank gRPC Service
    ---------------------------------------------------------------------------
    """

    @staticmethod
    def Credit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/upi.ReceiverBankService/Credit',
            upi__pb2.CreditRequest.SerializeToString,
            upi__pb2.CreditResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
